# Generated by Django 4.0.1 on 2022-01-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('C', 'closed'), ('R', 'reversed'), ('P', 'pending')], max_length=2),
        ),
    ]
