# Generated by Django 4.0.1 on 2022-01-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('C', 'closed'), ('R', 'reversed'), ('P', 'pending')], max_length=1),
        ),
    ]
